function allLabels = assembleLabels()

  %% this is because the code in computeStyleParams fails to write the
  %% labels properly, but for now I don't want to touch that code, so
  %% I replicate and fix that functionality here 

  %% names of the computed-from-transcipts features ;  no longer used 
  aaronFeatNames = { ...
	       'Self Speaking Fraction',  ...
	       'Self Average Word Duration', ...
	       'Self 1st Person Frac', ...
	       'Self 2nd Person Frac', ...
	       'Self BC Frac', ...
	       'Self Filler Frac', ...
	       'Inte Speaking Fraction', ...
	       'Inte Average Word Duration', ...
	       'Inte 1st Person Frac', ...
	       'Inte 2nd Person Frac', ...
	       'Inte BC Frac', ...
	       'Inte Filler Frac'
		   };

  %% prosodic dimension names 
  names = {'+ other has turn - self has turn', ... 
	   '+ enthusiasm overlap - silence/delay', ...
	   '+ turn yield - turn take', ...
	   '+ backchannelling - talking/BC cueing', ...
	   '+ topic continuation - topic closing', ...
	   '+ positive assessment - topic development', ...
	   '+ indifference - empathy bid', ...
	   '+ bipartite construction - fillers', ...
	   '+ p.a. turn yield - p.a. turn take', ...
	   '+ fillers - late peaks', ...
	   '+ bookended narrow pitch - meta comment', ...
	   '+ receiving action cue - minor third cue' ...
	  };

  %% this needs to match what's in computeStyleParams!!
  intervals = intervalsForCSP();

  nIntervals = size(intervals,1);
  labels = {};

  %%for i = 1:length(aaronFeatNames)
  %%    labels{end+1} = aaronFeatNames{i};
  %%  end
  
  for d = 1:length(names)
    nameCell = names(d);
    for i = 1:nIntervals
      labels{end+1} = sprintf('pdim%2d (%s) frac in %.1f~%.1f', ...
			      d, nameCell{1}, intervals(i,1), intervals(i,2));
    end
  end
  allLabels = labels;
  save allLabels;
end
  
